version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  python-app:
    build:
      context: .
    container_name: python-app-container
    ports:
      - "8501:8501"
    depends_on:
      - redis

volumes:
  redis-data:
